version: "3.9"
services:
  postgres:
    container_name: postgres_sees
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: