import { Prisma, Semester, Year } from '@prisma/client';

export const coursesJson: Prisma.CourseCreateInput[] = [
  {
    name: 'Engineering Pure Mathematics I',
    unit: 3,
    courseCode: 'GEG101',
    year: Year.ONE,
    semester: Semester.FIRST,
  },

  {
    name: 'Engineering Applied Maths1',
    unit: 3,
    courseCode: 'GEG103',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Workshop Practice',
    unit: 1,
    courseCode: 'MEG101',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Introductory Physics I',
    unit: 3,
    courseCode: 'FSC105',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Physical Chemistry',
    unit: 3,
    courseCode: 'FSC102',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Technical Drawing I',
    unit: 2,
    courseCode: 'MEG103',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Use of English I',
    unit: 2,
    courseCode: 'GST105',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Philosophy and Logic',
    unit: 2,
    courseCode: 'GST102',
    year: Year.ONE,
    semester: Semester.FIRST,
  },
  {
    name: 'Engineering Pure Maths II',
    unit: 3,
    courseCode: 'GEG102',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Engineering Applied Maths II',
    unit: 3,
    courseCode: 'GEG104',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Workshop Practice',
    unit: 2,
    courseCode: 'MEG102',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Technical Drawing II',
    unit: 2,
    courseCode: 'MEG104',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Introductory Physics II',
    unit: 3,
    courseCode: 'PHS102',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Introductory Physics III',
    unit: 2,
    courseCode: 'PHS101',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Physics Laboratory',
    unit: 2,
    courseCode: 'PHS103',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Use of English',
    unit: 2,
    courseCode: 'GST106',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Philosophy',
    unit: 2,
    courseCode: 'GST104',
    year: Year.ONE,
    semester: Semester.SECOND,
  },
  {
    name: 'Fundamental of Electrical Engineering I',
    unit: 2,
    courseCode: 'EEG201',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Signals and Systems Theory',
    unit: 2,
    courseCode: 'EEG203',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Electrical Engineering Materials',
    unit: 2,
    courseCode: 'EEG205',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Electrical Systems Graphic',
    unit: 2,
    courseCode: 'EEG207',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Fundamental of Electrical Engr. Laboratory',
    unit: 1,
    courseCode: 'EEG209',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Engineering Mathematics I',
    unit: 3,
    courseCode: 'GEG201',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'General African Studies',
    unit: 2,
    courseCode: 'GST201',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Thermodynamics',
    unit: 2,
    courseCode: 'MEG201',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Engineering Mechanics I (Statics)',
    unit: 2,
    courseCode: 'MEG205',
    year: Year.TWO,
    semester: Semester.FIRST,
  },
  {
    name: 'Fundamental of Electrical Engineering II',
    unit: 2,
    courseCode: 'EEG202',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Introduction to Switching and Logic Systems',
    unit: 2,
    courseCode: 'EEG204',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Computer Programming I',
    unit: 2,
    courseCode: 'EEG206',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Physical Electronics',
    unit: 2,
    courseCode: 'EEG208',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Fundamental of Electrical Engineering II Laboratory',
    unit: 1,
    courseCode: 'EEG210',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Introductory Engineering Statistics',
    unit: 3,
    courseCode: 'GEG202',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'General African Studies II',
    unit: 2,
    courseCode: 'GST202',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Fluid Mechanics',
    unit: 3,
    courseCode: 'MEG202',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Engineering Mechanics II (Dynamics)',
    unit: 2,
    courseCode: 'MEG208',
    year: Year.TWO,
    semester: Semester.SECOND,
  },
  {
    name: 'Circuits and Systems I',
    unit: 2,
    courseCode: 'EEG 301',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Electronic Circuits I',
    unit: 2,
    courseCode: 'EEG 305',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Instrumentation and Measurement I',
    unit: 2,
    courseCode: 'EEG 307',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Energy Conversion',
    unit: 2,
    courseCode: 'EEG 309',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Computer Programming II',
    unit: 2,
    courseCode: 'EEG 311',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Energy Conversion Laboratory',
    unit: 1,
    courseCode: 'EEG 313',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Electronic Circuits I Laboratory',
    unit: 1,
    courseCode: 'EEG 315',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Engineering Mathematics II ',
    unit: 2,
    courseCode: 'GEG 301',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Entrepreneurship and Good Governance I',
    unit: 2,
    courseCode: 'GST307',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Civil Engineering Technology',
    unit: 3,
    courseCode: 'CEG 311',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Mechanical Engineering Technology',
    unit: 3,
    courseCode: 'MEG 311',
    year: Year.THREE,
    semester: Semester.FIRST,
  },
  {
    name: 'Circuit and System II',
    unit: 2,
    courseCode: 'EEG 302',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Transmission Lines and Filters',
    unit: 2,
    courseCode: 'EEG 304',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Electronic Circuits II',
    unit: 2,
    courseCode: 'EEG 306',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Power Electronics',
    unit: 2,
    courseCode: 'EEG 308',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Electrical Drives',
    unit: 2,
    courseCode: 'EEG 310',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Instrumentation and Measurement II',
    unit: 2,
    courseCode: 'EEG 312',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Logic Design of Digital Systems',
    unit: 2,
    courseCode: 'EEG 314',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Electronic Circuits II Laboratory',
    unit: 1,
    courseCode: 'EEG 316',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Operational Method',
    unit: 2,
    courseCode: 'GEG 302',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Electrical Drives Laboratory',
    unit: 1,
    courseCode: 'EEG 318',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
  {
    name: 'Electrical Engineering Technology',
    unit: 3,
    courseCode: 'EEG 320',
    year: Year.THREE,
    semester: Semester.SECOND,
  },
];
